### ISSUE TITLE
Error "x509 failed to load system roots"

### ISSUE THREAD

**Issue by ninlil** [dexidp/dex#1057] opened 2017-09-07 14:49 UTC
I'm trying to follow the documentation on starting dex in a new Azure-Kubernetes-cluster.
I can't find out why because your Dockerfile says you use 'alpine' and that it should fetch the latest (at the time) ssl-certificates.

Am I doing something wrong or have I misunderstood, or what could it be?

### Logs
> failed to initialize server: server: Failed to open connector google: failed to open connector: failed to create connector google: failed to get provider: Get https://accounts.google.com/.well-known/openid-configuration: x509: failed to load system roots and no roots provided

### Config:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: kube-net
data:
  config.yaml: |
    issuer: https://dev.DOMAIN.com/auth
    storage:
      type: sqlite3
      config:
        file: /var/dex/dex.db
    web:
      http: 0.0.0.0:5556
    connectors:
    - type: oidc
      id: google
      name: Google
      config:
        issuer: https://accounts.google.com
        clientID: "##################.apps.googleusercontent.com"
        clientSecret: "##################."
        redirectURI: https://dev.DOMAIN.com/auth/callback
    oauth2:
      skipApprovalScreen: true
    logger:
      level: "debug"
      format: "json"
```
### Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dex
  namespace: kube-net
  labels:
    app: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - image: quay.io/coreos/dex:v2.6.1
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/config.yaml"]
        ports:
        - containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc
        - name: data
          mountPath: /var/dex
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
      - name: data
        emptyDir: {}
```

**Comment by ericchiang** [comment] 2017-09-07 20:09
Odd, this works with wget

```
$ docker run -it --rm --entrypoint=wget quay.io/coreos/dex:v2.6.1 -O -- https://accounts.google.com/.well-known/openid-configuration
Connecting to accounts.google.com (216.58.194.173:443)
--                   100% |*********************************************************************************************************************************************************************************************|  1039   0:00:00 ETA
```

Will investigate.

**Comment by nabokihms** [comment] 2022-08-29 06:35
I tried this with the latest version of Dex (v2.33.0) and could not reproduce it.
I'm going to close this issue. If it is still relevant, please feel free to reopen it.

**Closed by nabokihms** 2022-08-29 06:35 UTC
Labels: kind/bug
