### ISSUE TITLE
dex ldap demo || ldap_bind: Invalid credentials (49)

### ISSUE THREAD

**Issue by foreversunyao** [dexidp/dex#1581] opened 2019-11-08 11:12 UTC
Hi , 
    I am new here, and I did example for ldap according to https://github.com/dexidp/dex/blob/master/Documentation/connectors/ldap.md

    When ldap and example-app was running, I ran below command  with password "admin" , but it failed . 
```
ldapsearch -x -LLL -H 'ldap://localhost:10389' -D cn=admin,dc=example,dc=com  -W -x  -b 'dc=example,dc=org' 'userName=*'
Enter LDAP Password:
ldap_bind: Invalid credentials (49)
```
    And also for the website portal demo(janedoe@example.com/foo), it failed as well.  
```
Internal Server Error
Login error: ldap: initial bind for user "cn=admin,dc=example,dc=org" failed: LDAP Result Code 49 "Invalid Credentials":

The debug log:
5dc54d28 do_bind: version=3 dn="cn=admin,dc=example,dc=org" method=128
5dc54d28 ==> bdb_bind: dn: cn=admin,dc=example,dc=org
5dc54d28 bdb_dn2entry("cn=admin,dc=example,dc=org")
5dc54d28 => bdb_dn2id("dc=example,dc=org")
5dc54d28 <= bdb_dn2id: get failed: DB_NOTFOUND: No matching key/data pair found (-30988)
```

    I don't know if I missed something...
    Thanks for help.

**Comment by nabokihms** [comment] 2022-08-28 16:16
I checked the current demo and it seems ok to me. Because of the issue opening date I assume the problem is no longer relevant. 
I'm going to close this issue. If you still need help, fell free to reopen it.

**Closed by nabokihms** 2022-08-28 16:16 UTC
