### ISSUE TITLE
DEX signing

### ISSUE THREAD

**Issue by ppolicherla** [dexidp/dex#1310] opened 2018-10-08 20:02 UTC
So I am running dex with an ldap server and I can log into my app. And I get the following token

> eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwM2RiN2FmMTJjNGYxNWI4ZWU4OGJiZTg4YWMwMDQyOWNmNzQ4NmMifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvYXV0aCIsInN1YiI6IkNpUTNOamd3T1RjMU1pMDJZVEUwTFRRNE56TXRZV1l5TWkwMlpqSTNZekpsTVdFM09HSVNCR3hrWVhBIiwiYXVkIjoiYWlwLWFkbWluLWFwcC13ZWIiLCJleHAiOjE1MzkxMTQ0MzksImlhdCI6MTUzOTAyODAzOSwibm9uY2UiOiJVb2RyWTNrWkIwOVVTOGdVN2NwbXhHbVB0emZWWUdqQyIsImF0X2hhc2giOiJoSjM0eGZLTFZMNEVva1NEbTc0MVZnIiwiZW1haWwiOiJqZWZmdGhvbXBzb24xOTcxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJncm91cHMiOlsiQklTOkFkbWluIiwiVU1TOkFkbWluIiwiQUlQOkFiYm90dCJdLCJ0ZW5hbnRzIjpbIjhhZDc5NDk1LWE5ODAtNDU0My05M2U4LTg1ZDc2MDhiZDMzNiJdLCJuYW1lIjoiQWJib3R0IEFkbWluIn0.6fXpfcS4ZrEQlU64vDNa_Gvu9sAdye0TrRACs90ItvGUEPQJbZggJG6CvdQu7nDQm4BMqhcjgca6KXIW_5aGYOfXsyUizR0Eaa5j2y8ORQ8sLuMt7hRN0AZ5JsyZLdV1TeCFDmtAIn28tFtR0mtQ1AmvrWcH3YF2tttkUPsVUn3K0jqwls1QfcvIEnA2WmVSRJTrdar_-rdRHDNbdS4ILegD92F8bazThLoC-zkPPWIzYNvyeiRU75uoafx-6ByZ4ZMrr2907VdHEQgNbkT5qxQ8dOQenOV7JRhtGZFvP3S3o6xq2Y5a90fRZirUHszFzDDy7G2A9PPXbXsSFfPh1A

Now the issue is that when I use the public keys that are generated from the key files i create with the gen-certs.sh I am still unable to get a verification. 
The following are the public keys I can create from the the private keys that the gen certs script give me

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqKmVE+gl48tdYeT6sKco
ISUX7omlczBPepn3R9fH/AN2EB7oO/7h8zUBxZeBzVgJBTK48uXoGJzkTEzhCgwB
rB99TXNsrjyTsHKF3VrkQKIWm+1cZe9YlW/wprZiEUqQdcPaIxKzlUoBHU/4p4df
H1PtqGo4+PpSpntnRXmI5Ef5dMwQMAD+A/IzdCeKpdzG4z+7mhT7yTekxzQKnEv2
U6e0WAICv0pJX5PkWD+3ibuWbDUt+ZHmUsYUfht1X2dmOAa44K7yubu+yrI2bnkL
N/zZxayCpC09iqkvW9fx1PWd0TxW+qPqvtbcKJwR+lsxWm4Ok6P1npomp2C2xAJu
tQIDAQAB
-----END PUBLIC KEY-----

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAor7Zk2KJxcpwBeCpg5uc
BWjQYS74v0qgt8GiQmxazh12vheBsrdP0LZJIM73577UrVz0SPwAz9hhe7Hvrq64
3aOruStgmgfU9IgZcwr14D01hRroMwIoLBK+1aAa1irUNGMcUS3QAZHkaMqoNUzM
EvWcGpoWlh/e9Mi+VROGDORJgarT5lo0aOTsCL/stByH1ltiV0OYSijVaWKirsv7
fz7PrlrdvFHc8qNIIqVqfNsCbxXHjQUTNx1fEBLiUSAE/6wvU6iU51E8SlcujpVm
hAk+Md+rLyWoHCsOfmpy2WTu0aB4wbzPqgIwFLzUBSYgaHCjysmltjxce8vSMd9k
VwIDAQAB
-----END PUBLIC KEY-----

I know that my issue is not having the files actually being used to sign tokens. But how can I fix this? is it in the Config-ldap.yaml file?

**Comment by srenatus** [comment] 2018-10-09 09:50
> I know that my issue is not having the files actually being used to sign tokens. But how can I fix this? is it in the Config-ldap.yaml file?

I believe that's _by design_. The key used to sign tokens is auto-generated, and managed by dex. It takes care of rotation, everything. If you want to retrieve the public key(s) used for signing tokens, that's `https://YOUR-DEX-SERVER/dex/keys`. It's not something you could _set_ or interfere with, you can only _get_ them, as far as I know.

Taking a step back -- what is it you're trying to do? Why do you _need_ to set the private key used for signing tokens?

**Comment by ppolicherla** [comment] 2018-10-09 14:09
I see, I figured that would be the case. I have two separate apps running, dex and my back end app. I want to be able to verify the signature of the token using my backend app which I would need the public keys for in my backend app. But if dex works the way you described I will have to look into another way of doing that.

**Comment by srenatus** [comment] 2018-10-09 14:41
> I want to be able to verify the signature of the token using my backend app which I would need the public keys for in my backend app.

I don't see the problem here, as dex exposes **those public keys**. You can use go-oidc or some other library to verify the id tokens' signature, using the exposed public keys.

You should be able to do something [like what the README describes here](https://github.com/coreos/go-oidc),

```go
    provider, err := oidc.NewProvider(ctx, "https://YOUR-DEX-SERVER/dex")
    if err != nil {
        // handle error
    }
    var verifier = provider.Verifier(&oidc.Config{ClientID: clientID})

    // Parse and verify ID Token payload.
    idToken, err := verifier.Verify(ctx, rawIDToken)
    if err != nil {
        // handle error
    }

    // Extract custom claims
    var claims struct {
        Email    string `json:"email"`
        Verified bool   `json:"email_verified"`
    }
    if err := idToken.Claims(&claims); err != nil {
        // handle error
    }
```

**Comment by ppolicherla** [comment] 2018-10-09 15:09
Ok well is this something that I can implement outside of dex or do I need it inside of go? I am trying to implement the verification on a separate app, and will this account for the rotations?

**Comment by srenatus** [comment] 2018-10-09 15:16
This could totally be done in a different language. go-oidc just happens to be a client-lib I know that can do this:
- get the public keys periodically
- use them to verify a jwt id_token's signature

There surely are others. You shouldn't have to change dex for this.

**Comment by ppolicherla** [comment] 2018-10-09 15:27
Cool. Just to see if I understand what you are saying. I will be able to implement a library in my main app that will be able to grab the keys from the dex endpoint and then convert them to PEM format and use them for verification. This will work as long as I check for these keys periodically to avoid rotation mismatching. And this can be implemented outside of the dex app itself?

**Comment by srenatus** [comment] 2018-10-09 15:37
@ppolicherla That is correct. Any OpenID Connect library should be able to work with Dex's endpoints, without changing anything in Dex.

**Comment by ppolicherla** [comment] 2018-10-09 16:19
@srenatus Awesome thank you man, I am sorry if my question seemed stupid. I don't know why I am having a hard time wrapping my head around dex. But this helps out a lot.

**Comment by ppolicherla** [comment] 2018-10-09 17:34
@srenatus Sorry I have one more question about this implementation, will they be able to interpret the keys in the PEM format as required by the RS256 standard?

**Comment by ppolicherla** [comment] 2018-10-10 13:57
Awesome, this definitely gives me some ideas on how to move forward. Thank you!!!!!

**Comment by srenatus** [comment] 2018-10-10 14:17
@ppolicherla 🎉 -- can we close this? 😉

**Comment by ppolicherla** [comment] 2018-10-10 18:33
Yeah I believe that all my questions have been answered adequately, and the issue can be closed. Thank you

**Comment by srenatus** [comment] 2018-10-10 18:52
:tada: :smiley:

**Closed by srenatus** 2018-10-10 18:52 UTC
