### ISSUE TITLE
[LDAP] Login failure when password contains some special characters

### ISSUE THREAD

**Issue by kumashiro** [dexidp/dex#3456] opened 2024-04-07 14:47 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

HEAD

### Storage Type

SQLite

### Installation Type

Official container image

### Expected Behavior

Logins with all supported special characters should succeed when using LDAP connector.

### Actual Behavior

With LDAP connector, login fails if user password contains any of the characters from the set `()*\`. This is caused by an unnecessary escape of password in connector/ldap/ldap.go:476. Password is not passed in a LDAP query string, therefore it does not need and should not be escaped.

Applying the patch below fixes the problem:

```
diff --git a/connector/ldap/ldap.go b/connector/ldap/ldap.go
index f0aa7eff..bb434a6c 100644
--- a/connector/ldap/ldap.go
+++ b/connector/ldap/ldap.go
@@ -473,7 +473,6 @@ func (c *ldapConnector) Login(ctx context.Context, s connector.Scopes, username,
        )

        username = ldap.EscapeFilter(username)
-       password = ldap.EscapeFilter(password)

        err = c.do(ctx, func(conn *ldap.Conn) error {
                entry, found, err := c.userEntry(conn, username)
```

**Comment by nabokihms** [comment] 2024-04-09 09:37
Hello, it is a duplicate of https://github.com/dexidp/dex/issues/3436

**Closed by nabokihms** 2024-04-09 09:37 UTC
