### ISSUE TITLE
Allow dex to start its server if one or more connectors fails to initiialize

### ISSUE THREAD

**Issue by dlipovetsky** [dexidp/dex#2787] opened 2023-01-12 20:36 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Dex [initializes every connector](https://github.com/dexidp/dex/blob/b6cc099305702782e6dc86284e408a464cc76fe9/server/server.go#L294-L298) when its server starts. If one connector fails to initialize, dex [exits](https://github.com/dexidp/dex/blob/6da5187b474a967d4b096c5a137de048f00f6bbc/cmd/dex/serve.go#L330-L333).

Dex exits _even if other connectors are available and successfully initialized_. This provides a bad user experience. For example, if a user adds a new OIDC connector but misconfigures it, existing users connecting via a correctly configured LDAP connector will be unable to authenticate. 

By comparison, once the server is running, dex may need to [initialize a new connector](https://github.com/dexidp/dex/blob/b6cc099305702782e6dc86284e408a464cc76fe9/server/server.go#L625-L633). If that connector fails to initialize, dex does not exit, but only returns an error to the client.

It therefore appears safe for dex to start its server if one or more connectors fails to initialize.

### Proposed Solution

Allow dex to start its server if one or more connectors fails to initiialize.

If the current behavior (exiting) should remain the default, the new behavior can be enabled with a flag.

**Comment by nabokihms** [comment] 2023-01-13 15:46
Hello! it seems like a duplicate of https://github.com/dexidp/dex/issues/1723 
The issue is valid, and we appreciate any help with resolving it.

Closing it as a duplicate.

**Closed by nabokihms** 2023-01-13 15:46 UTC

**Comment by dlipovetsky** [comment] 2023-01-13 17:33
> Hello! it seems like a duplicate of #1723 The issue is valid, and we appreciate any help with resolving it.
> 
> Closing it as a duplicate.

Thanks for triaging!

Sorry, I missed #1723. To be fair, a few connectors make network calls during initialization: OIDC, Google, and OpenShift. And all connectors could, in general, fail to initialize.

I can copy my description over to #1723.
