### ISSUE TITLE
Cannot specify MySQL port

### ISSUE THREAD

**Issue by shijianjs** [dexidp/dex#2098] opened 2021-04-25 09:31 UTC
#### Expected behavior (what you expected to happen)
Mysql can connect and init successful.
#### Actual behavior (what actually happened)
Mysql with port 3308 can not connect.
#### Steps to reproduce

1. ...
2. ...
3. ...

#### Environment

- Dex version: v2.28.1
- Storage type: mysql
- Installation type (official docker image, helm chart, etc.): docker image

#### Additional information for debugging (if necessary)

<details><summary>Configuration</summary><br><pre>
---
# first  storage config
## conn str: root:123456@tcp([myip])/dex_db?checkConnLiveness=false&parseTime=true&tls=false&maxAllowedPacket=0&transaction_isolation=%27SERIALIZABLE%27
storage:
  type: mysql
  config:
    host: "[myip]"
    port: 3308
    database: "dex_db"
    user: "root"
    password: "xxxxxx"
    maxOpenConns: 5
    maxIdleConns: 3
    connMaxLifetime: 30
    connectionTimeout: 3
    ssl:
      mode: "false"
# second storage config
## conn str: root:123456@tcp([myip]:3308)/dex_db?checkConnLiveness=false&parseTime=true&tls=false&maxAllowedPacket=0&transaction_isolation=%27SERIALIZABLE%27
storage:
  type: mysql
  config:
    # Add port to host can connect successful, but init error.
    host: "[myip]:3308"
    port: 3308
    database: "dex_db"
    user: "root"
    password: "xxxxxxx"
    maxOpenConns: 5
    maxIdleConns: 3
    connMaxLifetime: 30
    connectionTimeout: 3
    ssl:
      mode: "false"

</pre></details>

<details><summary>Logs</summary><br><pre>
1. first  storage config error:
time="2021-04-25T09:19:52Z" level=info msg="config issuer: http://127.0.0.1:5556/dex"
failed to initialize storage: Error 1049: Unknown database 'dex_db'

2. second storage config error:
failed to initialize storage: failed to perform migrations: update migration table: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
</pre></details>

**Comment by sagikazarmark** [comment] 2021-04-25 10:14
So the first error seems obvious (you need to create a database) and I guess you've gotten past that.

The second error also doesn't seem to be a Dex issue. Your MySQL server is rejecting queries because you've reached the maximum amount of prepared statements. It's a global setting an you've apparently reached the limit. I don't know if it is because you run other applications using this MySQL server, but my bet is on that.

Try to increase that limit if you can, but keep in mind that it's there for a reason: making it too high can cause memory problems on your server.

You can also try using a different MySQL server for Dex.

These issues are often caused by applications, like Laravel. If you run a lot of those using this database, try putting ProxySQL in front of it.

Closing as this is not a Dex problem. Hope the above helps.

**Comment by shijianjs** [comment] 2021-04-26 02:27
https://github.com/dexidp/dex/blob/551229a986738ba71e9c2a6ba9a9c25b7db1f7ef/storage/sql/config.go#L227

- The first error is a config parse error, I can't find any code use `s.Port` in mysql open connection method. Different of 2 configs is host: "[myip]" -> "[myip]:3308", and the port config 3308 don't effective. 
- And test code with 3306 port just because it is mysql default port. I can connect to 3306 and can't find the dex_db because myip started two mysql in docker and export two prot: 3306, 3308.

Note the port:
```
# first config conn str: 
root:123456@tcp([myip])/dex_db?checkConnLiveness=false&parseTime=true&tls=false&maxAllowedPacket=0&transaction_isolation=%27SERIALIZABLE%27
# second config conn str: 
root:123456@tcp([myip]:3308)/dex_db?checkConnLiveness=false&parseTime=true&tls=false&maxAllowedPacket=0&transaction_isolation=%27SERIALIZABLE%27
```

**Comment by sagikazarmark** [comment] 2021-04-26 08:23
I see. Sorry, based on the logs and the description the issue wasn't obvious.

**Closed** 2021-04-27 23:23 UTC
Labels: area/storage, kind/bug
