### ISSUE TITLE
Add ppc64le support

### ISSUE THREAD

**Issue by mayurwaghmode** [dexidp/dex#2333] opened 2021-11-24 06:50 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

dex is not executable on ppc64le architecture.

### Proposed Solution

provide support for ppc64le arch.

**Comment by sagikazarmark** [comment] 2021-11-24 08:46
Duplicate of #1388

Please note that we currently don't have the bandwidth to support this architecture, even if we provide builds for it.

**Comment by mayurwaghmode** [comment] 2021-11-24 10:16
Ok! Do you have dex image built for ppc64le arch?

**Comment by sagikazarmark** [comment] 2021-12-01 16:36
No, we don't. Feel free to open a PR.

**Comment by nabokihms** [comment] 2022-08-28 16:32
Closed in https://github.com/dexidp/dex/pull/2620

**Closed by nabokihms** 2022-08-28 16:32 UTC
